name: Publish Addon to Marketplace
description: Publish a new Addon to the Jmix Marketplace
title: "[Add-On] "
labels: ["add-on"]
assignees:
  - knstvk
  - glebfox
body:
  - type: markdown
    attributes:
      value: |
        You want to publish a new add-on to the Jmix Marketplace? Great!

        In order to publish your add-on the process looks like this:

        1. Submit a new add-on via this form
        2. We will check the add-on and create a proxy maven repo on https://global.repo.jmix.io/
        3. You create a PR with the description of your add-on in the [add-on part](https://github.com/jmix-framework/jmix-website-content/tree/master/Content/Add-ons) of this repo
        4. We accept the PR and publish the content on the website

        If you want to do changes to your description, feel free to create another PR with your desired changes in this repository.

        Thanks for providing new features to the Jmix community. We value your contribution!
  - type: input
    id: addon-name
    attributes:
      label: Add-on Name
      value: My new Add-on
    validations:
      required: true
  - type: input
    id: github-repository
    attributes:
      label: Github Repository
      value: https://github.com/myuser/my-addon
    validations:
      required: true
